#ifndef BISON_Y_TAB_H
# define BISON_Y_TAB_H

#ifndef YYSTYPE
typedef union {
   int i;
   char *val;
   /*IPAddr *ip;*/
   MPPrefix *ip;
   ASt as;
} yystype;
# define YYSTYPE yystype
# define YYSTYPE_IS_TRIVIAL 1
#endif
# define	TKN_IP	257
# define	TKN_ASNUM	258
# define	TKN_ERROR	259
# define	TKN_STR	260
# define	TKN_INT	261
# define	TKN_DNSNAME	262
# define	TKN_FILTER	263
# define	TKN_WORD	264
# define	KW_IMPORT	265
# define	KW_EXPORT	266
# define	KW_EXPORT_GROUP	267
# define	KW_IMPORT_GROUP	268
# define	KW_PRINT_PREFIXES	269
# define	KW_PRINT_PREFIX_RANGES	270
# define	KW_PRINT_SUPER_PREFIX_RANGES	271
# define	KW_ASPATH_ACCESS_LIST	272
# define	KW_ACCESS_LIST	273
# define	KW_CONFIGURE_ROUTER	274
# define	KW_STATIC2BGP	275
# define	KW_SET	276
# define	KW_CISCO_MAP_NAME	277
# define	KW_JUNOS_POLICY_NAME	278
# define	KW_CISCO_PREFIX_ACL_NO	279
# define	KW_CISCO_ASPATH_ACL_NO	280
# define	KW_CISCO_PKTFILTER_ACL_NO	281
# define	KW_CISCO_COMMUNITY_ACL_NO	282
# define	KW_CISCO_ACCESS_LIST_NO	283
# define	KW_SOURCE	284
# define	KW_PREFERENCECEILING	285
# define	KW_CISCO_MAX_PREFERENCE	286
# define	KW_NETWORKS	287
# define	KW_V6NETWORKS	288
# define	KW_DEFAULT	289
# define	KW_CISCO_MAP_INC	290
# define	KW_CISCO_MAP_START	291
# define	KW_PKT_FILTER	292
# define	KW_OUTBOUND_PKT_FILTER	293
# define	KW_BCC_VERSION	294
# define	KW_BCC_MAX_PREFERENCE	295
# define	KW_BCC_ADVERTISE_NETS	296
# define	KW_BCC_ADVERTISE_ALL	297
# define	KW_BCC_FORCE_BACK	298
# define	KW_BCC_MAX_PREFIXES	299


extern YYSTYPE commandlval;

#endif /* not BISON_Y_TAB_H */
